application: townsita
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico
- url: /robots\.txt
  static_files: assets/robots.txt
  upload: assets/robots\.txt
- url: /assets/css
  static_dir: templates/assets/css
- url: /.*
  script: _go_app